// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyCat.Backend.Data;

#nullable disable

namespace SurveyCat.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260415151219_AddPersonaEntity")]
    partial class AddPersonaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodBarrioComarca")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("EsBarrio")
                        .HasColumnType("bit");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodBarrioComarca")
                        .IsUnique();

                    b.HasIndex("MunicipioId");

                    b.ToTable("BarriosComarcas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Caserio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodCaserio")
                        .HasColumnType("int");

                    b.Property<int>("ComarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodCaserio")
                        .IsUnique();

                    b.HasIndex("ComarcaId");

                    b.ToTable("Caserios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodDepto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodINIDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodDepto")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Diccionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Catalogo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Catalogo", "Nombre")
                        .IsUnique();

                    b.ToTable("Diccionarios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodINIDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMuni")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodMuni")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BarrioComarcaId")
                        .HasColumnType("int");

                    b.Property<int?>("CaserioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProfesionId")
                        .HasColumnType("int");

                    b.Property<string>("RegistradaEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.Property<int?>("TipoPersonaJuridicaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdaterUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BarrioComarcaId");

                    b.HasIndex("CaserioId");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasFilter("[Identificacion] IS NOT NULL");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ProfesionId");

                    b.HasIndex("TipoIdentificacionId");

                    b.HasIndex("TipoPersonaJuridicaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSector")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SectorDepto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SectorMuni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoSector")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId", "NumeroSector")
                        .IsUnique();

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("BarriosComarcas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Caserio", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.BarrioComarca", "Comarca")
                        .WithMany("Caserios")
                        .HasForeignKey("ComarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comarca");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Persona", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.BarrioComarca", "BarrioComarca")
                        .WithMany()
                        .HasForeignKey("BarrioComarcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Caserio", "Caserio")
                        .WithMany()
                        .HasForeignKey("CaserioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Profesion")
                        .WithMany()
                        .HasForeignKey("ProfesionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "TipoPersonaJuridica")
                        .WithMany()
                        .HasForeignKey("TipoPersonaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BarrioComarca");

                    b.Navigation("Caserio");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Municipio");

                    b.Navigation("Profesion");

                    b.Navigation("TipoIdentificacion");

                    b.Navigation("TipoPersonaJuridica");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Sector", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("Sectores")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.Navigation("Caserios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.Navigation("BarriosComarcas");

                    b.Navigation("Sectores");
                });
#pragma warning restore 612, 618
        }
    }
}
