// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyCat.Backend.Data;

#nullable disable

namespace SurveyCat.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260610203851_UpdateTipoConflictoIdFieldInConflictoEntity")]
    partial class UpdateTipoConflictoIdFieldInConflictoEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodBarrioComarca")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("EsBarrio")
                        .HasColumnType("bit");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodBarrioComarca")
                        .IsUnique();

                    b.HasIndex("MunicipioId");

                    b.ToTable("BarriosComarcas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Caserio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodCaserio")
                        .HasColumnType("int");

                    b.Property<int>("ComarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodCaserio")
                        .IsUnique();

                    b.HasIndex("ComarcaId");

                    b.ToTable("Caserios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Colindante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConflictoId")
                        .HasColumnType("int");

                    b.Property<long>("FichaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PresentaConflicto")
                        .HasColumnType("bit");

                    b.Property<int>("PuntoCardinalId")
                        .HasColumnType("int");

                    b.Property<int?>("ViaGestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConflictoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("PuntoCardinalId");

                    b.HasIndex("ViaGestionId");

                    b.HasIndex("FichaId", "PuntoCardinalId", "PersonaId")
                        .IsUnique();

                    b.ToTable("Colindantes");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Conflicto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ConEstado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FichaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoConflictoId")
                        .HasColumnType("int");

                    b.Property<int>("ViaGestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("ViaGestionId");

                    b.HasIndex("TipoConflictoId", "ViaGestionId", "ConEstado")
                        .IsUnique();

                    b.ToTable("Conflictos");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodDepto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodINIDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodDepto")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Diccionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Catalogo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Catalogo", "Nombre")
                        .IsUnique();

                    b.ToTable("Diccionarios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Ocupante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FichaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Item")
                        .HasColumnType("int");

                    b.Property<int>("ParentescoId")
                        .HasColumnType("int");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentescoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("FichaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Ficha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AreaEstimada")
                        .HasColumnType("float");

                    b.Property<int?>("BarrioComarcaId")
                        .HasColumnType("int");

                    b.Property<int?>("CaserioId")
                        .HasColumnType("int");

                    b.Property<string>("CodEncuesta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodParcela")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CoordinadorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionTipoUso")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EncuestadorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEncuesta")
                        .HasColumnType("datetime2");

                    b.Property<long>("InformanteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lote")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Manzana")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreFinca")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrigenTierraId")
                        .HasColumnType("int");

                    b.Property<bool>("PresentaConflicto")
                        .HasColumnType("bit");

                    b.Property<int?>("RelacionInformanteParcelaId")
                        .HasColumnType("int");

                    b.Property<int?>("RelacionInformantePropietarioId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<bool>("Servidumbre")
                        .HasColumnType("bit");

                    b.Property<int?>("ServidumbreAguaId")
                        .HasColumnType("int");

                    b.Property<int?>("ServidumbreOtraId")
                        .HasColumnType("int");

                    b.Property<int?>("ServidumbrePaseId")
                        .HasColumnType("int");

                    b.Property<int>("TecnicoCatastralId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEncuesta")
                        .HasColumnType("int");

                    b.Property<int?>("TipoUso")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdaterUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("VerificadoCoordinador")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BarrioComarcaId");

                    b.HasIndex("CaserioId");

                    b.HasIndex("CodEncuesta")
                        .IsUnique();

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("EncuestadorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("InformanteId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("OrigenTierraId");

                    b.HasIndex("RelacionInformanteParcelaId");

                    b.HasIndex("RelacionInformantePropietarioId");

                    b.HasIndex("SectorId");

                    b.HasIndex("ServidumbreAguaId");

                    b.HasIndex("ServidumbreOtraId");

                    b.HasIndex("ServidumbrePaseId");

                    b.HasIndex("TecnicoCatastralId");

                    b.HasIndex("UnidadMedidaId");

                    b.HasIndex("UserId");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodINIDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMuni")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodMuni")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BarrioComarcaId")
                        .HasColumnType("int");

                    b.Property<int?>("CaserioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProfesionId")
                        .HasColumnType("int");

                    b.Property<string>("RegistradaEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.Property<int?>("TipoPersonaJuridicaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdaterUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BarrioComarcaId");

                    b.HasIndex("CaserioId");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasFilter("[Identificacion] IS NOT NULL");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("ProfesionId");

                    b.HasIndex("TipoIdentificacionId");

                    b.HasIndex("TipoPersonaJuridicaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.PersonalEncuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brigada")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("PersonalEncuestas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Propietario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AreaTitulada")
                        .HasColumnType("float");

                    b.Property<string>("Asiento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AutorDocumento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("EspecificarPerfil")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<long>("FichaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Finca")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Hijas")
                        .HasColumnType("int");

                    b.Property<int?>("Hijos")
                        .HasColumnType("int");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PresentaDocumento")
                        .HasColumnType("bit");

                    b.Property<int>("TipoDerecho")
                        .HasColumnType("int");

                    b.Property<string>("Tomo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UnidadMedidaId");

                    b.HasIndex("FichaId", "PersonaId")
                        .IsUnique();

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSector")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SectorDepto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SectorMuni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoSector")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId", "NumeroSector")
                        .IsUnique();

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("BarriosComarcas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Caserio", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.BarrioComarca", "Comarca")
                        .WithMany("Caserios")
                        .HasForeignKey("ComarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comarca");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Colindante", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Conflicto")
                        .WithMany()
                        .HasForeignKey("ConflictoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Ficha", "Ficha")
                        .WithMany("Colindantes")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "PuntoCardinal")
                        .WithMany()
                        .HasForeignKey("PuntoCardinalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "ViaGestion")
                        .WithMany()
                        .HasForeignKey("ViaGestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conflicto");

                    b.Navigation("Ficha");

                    b.Navigation("Persona");

                    b.Navigation("PuntoCardinal");

                    b.Navigation("ViaGestion");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Conflicto", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Ficha", "Ficha")
                        .WithMany("Conflictos")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "TipoConflicto")
                        .WithMany()
                        .HasForeignKey("TipoConflictoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "ViaGestion")
                        .WithMany()
                        .HasForeignKey("ViaGestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");

                    b.Navigation("TipoConflicto");

                    b.Navigation("ViaGestion");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Ocupante", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Ficha", "Ficha")
                        .WithMany("Familias")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Parentesco")
                        .WithMany()
                        .HasForeignKey("ParentescoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");

                    b.Navigation("Parentesco");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Ficha", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.BarrioComarca", "BarrioComarca")
                        .WithMany("Fichas")
                        .HasForeignKey("BarrioComarcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Caserio", "Caserio")
                        .WithMany("Fichas")
                        .HasForeignKey("CaserioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.PersonalEncuesta", "Coordinador")
                        .WithMany("FichasCoordinador")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.PersonalEncuesta", "Encuestador")
                        .WithMany("FichasEncuestador")
                        .HasForeignKey("EncuestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Persona", "Informante")
                        .WithMany("Fichas")
                        .HasForeignKey("InformanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("Fichas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "OrigenTierra")
                        .WithMany()
                        .HasForeignKey("OrigenTierraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "RelacionInformanteParcela")
                        .WithMany()
                        .HasForeignKey("RelacionInformanteParcelaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "RelacionInformantePropietario")
                        .WithMany()
                        .HasForeignKey("RelacionInformantePropietarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Sector", "Sector")
                        .WithMany("Fichas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "ServidumbreAgua")
                        .WithMany()
                        .HasForeignKey("ServidumbreAguaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "ServidumbreOtra")
                        .WithMany()
                        .HasForeignKey("ServidumbreOtraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "ServidumbrePase")
                        .WithMany()
                        .HasForeignKey("ServidumbrePaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.PersonalEncuesta", "TecnicoCatastral")
                        .WithMany("FichasTecnicoCatastral")
                        .HasForeignKey("TecnicoCatastralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.User", null)
                        .WithMany("Fichas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BarrioComarca");

                    b.Navigation("Caserio");

                    b.Navigation("Coordinador");

                    b.Navigation("Encuestador");

                    b.Navigation("Estado");

                    b.Navigation("Informante");

                    b.Navigation("Municipio");

                    b.Navigation("OrigenTierra");

                    b.Navigation("RelacionInformanteParcela");

                    b.Navigation("RelacionInformantePropietario");

                    b.Navigation("Sector");

                    b.Navigation("ServidumbreAgua");

                    b.Navigation("ServidumbreOtra");

                    b.Navigation("ServidumbrePase");

                    b.Navigation("TecnicoCatastral");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Persona", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.BarrioComarca", "BarrioComarca")
                        .WithMany()
                        .HasForeignKey("BarrioComarcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Caserio", "Caserio")
                        .WithMany()
                        .HasForeignKey("CaserioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("Personas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Profesion")
                        .WithMany()
                        .HasForeignKey("ProfesionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "TipoPersonaJuridica")
                        .WithMany()
                        .HasForeignKey("TipoPersonaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BarrioComarca");

                    b.Navigation("Caserio");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Municipio");

                    b.Navigation("Profesion");

                    b.Navigation("TipoIdentificacion");

                    b.Navigation("TipoPersonaJuridica");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.PersonalEncuesta", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.User", "User")
                        .WithOne("PersonalEncuesta")
                        .HasForeignKey("SurveyCat.Shared.Entities.PersonalEncuesta", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Propietario", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurveyCat.Shared.Entities.Ficha", "Ficha")
                        .WithMany("Propietarios")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurveyCat.Shared.Entities.Diccionario", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Documento");

                    b.Navigation("Ficha");

                    b.Navigation("Persona");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Sector", b =>
                {
                    b.HasOne("SurveyCat.Shared.Entities.Municipio", "Municipio")
                        .WithMany("Sectores")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.BarrioComarca", b =>
                {
                    b.Navigation("Caserios");

                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Caserio", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Ficha", b =>
                {
                    b.Navigation("Colindantes");

                    b.Navigation("Conflictos");

                    b.Navigation("Familias");

                    b.Navigation("Propietarios");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Municipio", b =>
                {
                    b.Navigation("BarriosComarcas");

                    b.Navigation("Fichas");

                    b.Navigation("Personas");

                    b.Navigation("Sectores");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Persona", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.PersonalEncuesta", b =>
                {
                    b.Navigation("FichasCoordinador");

                    b.Navigation("FichasEncuestador");

                    b.Navigation("FichasTecnicoCatastral");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.Sector", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("SurveyCat.Shared.Entities.User", b =>
                {
                    b.Navigation("Fichas");

                    b.Navigation("PersonalEncuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
